name: DevOps CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check website files
        run: |
          echo "Checking website..."
          test -f index.html
          echo "index.html exists"

       - name: Test website content
        run: |
          grep -q "<html" index.html
          grep -q "DevOps" index.html
          echo "Website content test passed"
